### ISSUE TITLE
Invalid JSON when I run aws ssm register-task-with-maintenance-window command

### ISSUE THREAD

**Issue by ameyaagashe** [awsdocs/aws-systems-manager-user-guide#111]
I am running the below command and it is reporting an error **Invalid JSON:**

**AWS SSM Command:**
```
 aws ssm register-task-with-maintenance-window --window-id mw-06344a0189162e0b3 --targets Key=WindowTargetIds,Values=ae5c621a-17d8-454f-977f-46298f1e6eb8 --task-arn AWS-RunPatchBaseline --service-role-arn arn:aws:iam::xxxxxxxxxxxxx:role/AmazonSSMRoleForInstancesQuickSetup --task-type RUN_COMMAND --max-concurrency 2 --max-errors 1 --priority 1 --task-invocation-parameters '{\"Operation\":{\"Values\":[\"Install\"]}}'
```

**Error:**
```
Error parsing parameter '--task-invocation-parameters': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
JSON received: {\"Operation\":{\"Values\":[\"Install\"]}}
```

I'm using the AWS Documentation reference below:
https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-patch-cliwalk.html

Now, I **changed from single quotes to double quotes** but no charm, it still fails now with not using, correct Operation"

**AWS SSM Command**
```
aws ssm register-task-with-maintenance-window --window-id $grpa_maint_window --targets "Key=WindowTargetIds,Values=$reg_grpa_tar_wind_id" --task-arn "AWS-RunPatchBaseline" --service-role-arn "arn:aws:iam::xxxxxxxxxxxxx:role/AmazonSSMRoleForInstancesQuickSetup" --task-type "RUN_COMMAND" --max-concurrency 2 --max-errors 1 --priority 1 --task-invocation-parameters "{\"Operation\":{\"Values\":[\"Install\"]}}"
```

**Error:**
```
Parameter validation failed:
Unknown parameter in TaskInvocationParameters: "Operation", must be one of: RunCommand, Automation, StepFunctions, Lambda
```

Can you please update the documentation with correct example please.

**Comment by JimbroAmazon** [comment]
Hi Ameya,
Thanks for sending this feedback. I'm going to set up an environment and see if I can repro your issue. But before I do so, would you mind testing one thing for me? Could you change your last parameter in the command from --task-invocation-parameters to --task-parameters "{\"Operation\":{\"Values\":[\"Install\"]}}"

Please let me know if that works. Thanks!

**Comment by bcxpro** [comment]
I think that the part of the quotes and escape characters differs depending on the shell you are using and is not valid, for different reasons,  neither on Linux/bash nor Windows/CMD.

If you pass  `'{\"Operation\":{\"Values\":[\"Install\"]}}'`as an argument on CMD, the program receives: `'{"Operation":{"Values":["Install"]}}'` (note that there are single quotes, which makes the JSON document invalid)

The result of calling the actual aws ssm command is:
`Error parsing parameter '--task-invocation-parameters': Expected: '=', received: ''' for input:
'{"Operation":{"Values":["Install"]}}'`

If you pass  `'{\"Operation\":{\"Values\":[\"Install\"]}}'` as an argument on bash, the program receives: `{\"Operation\":{\"Values\":[\"Install\"]}}` (this is because the \ inside single quotes in bash is not acting as an escape character)

The result of calling the aws ssm command is:
`Error parsing parameter '--task-invocation-parameters': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
JSON received: {\"Operation\":{\"Values\":[\"Install\"]}}`

**With the proposed modification:**
Passing `"{\"Operation\":{\"Values\":[\"Install\"]}}"` via CMD, the program receives `{"Operation":{"Values":["Install"]}}`. Valid JSON.

The result is that the document 
`Parameter validation failed:
Unknown parameter in TaskInvocationParameters: "Operation", must be one of: RunCommand, Automation, StepFunctions, Lambda`

Passing `"{\"Operation\":{\"Values\":[\"Install\"]}}"` via bash,  the program receives `{"Operation":{"Values":["Install"]}}{"Operation":{"Values":["Install"]}}`. Valid JSON.

Result:
`Parameter validation failed:
Unknown parameter in TaskInvocationParameters: "Operation", must be one of: RunCommand, Automation, StepFunctions, Lambda`

**Comment by JimbroAmazon** [comment]
Thanks everyone. We've created a ticket in our internal system to update the example so I'm going to close this issue. Also, here is an example of --task-invocation-parameters that might be useful: https://docs.aws.amazon.com/systems-manager/latest/userguide/mw-cli-tutorial-tasks.html

**Comment by ameyaagashe** [comment]
@JimbroAmazon If I use --task-parameters that still does not work,.
```
aws ssm register-task-with-maintenance-window --window-id $grpa_maint_window --targets "Key=WindowTargetIds,Values=$reg_grpa_tar_wind_id" --task-arn "AWS-RunPatchBaseline" --service-role-arn "arn:aws:iam::xxxxxxxxxxxxxxxxxxxxxx:role/AmazonSSMRoleForInstancesQuickSetup" --task-type "RUN_COMMAND" --max-concurrency 2 --max-errors 1 --priority 1 --task-parameters '{\"Operation\":{\"Values\":[\"Install\"]}}'
+ aws ssm register-task-with-maintenance-window --window-id mw-086bfbb3f3181ec38 --targets Key=WindowTargetIds,Values=102fcef1-7c14-4a54-823b-cc01a637ddb5 --task-arn AWS-RunPatchBaseline --service-role-arn arn:aws:iam::xxxxxxxxxxxxxxxxxxxxx:role/AmazonSSMRoleForInstancesQuickSetup --task-type RUN_COMMAND --max-concurrency 2 --max-errors 1 --priority 1 --task-parameters '{\"Operation\":{\"Values\":[\"Install\"]}}'

Error parsing parameter '--task-parameters': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
JSON received: {\"Operation\":{\"Values\":[\"Install\"]}}
```

**Comment by ameyaagashe** [comment]
@JimbroAmazon The example you have provided is for the task-arn AWS-RunShellScript, do you an example for AWS-RunPatchBaseline? If yes then kindly suggest. Thanks in advance.

**Comment by mark-amzn** [comment]
@ameyaagashe 

If you're running the command on Linux/bash, try this format:

`aws ssm register-task-with-maintenance-window  --window-id mw-00897dfab9EXAMPLE  --targets "Key=WindowTargetIds,Values=ff3ef102-eb72-4b56-ad8f-dcc7cEXAMPLE" --task-arn "AWS-RunPatchBaseline" --task-type "RUN_COMMAND"  --max-concurrency 2  --max-errors 1 --priority 1 --task-invocation-parameters "RunCommand={Parameters={Operation=Install}}"`

Note that this is using `--task-invocation-parameters`, not `--task-parameters`.  I've also omitted `--service-role-arn` because I'm letting the command use the service-linked role, but you can of course specify a different role as you did in your examples.

We're working on getting the walkthrough updated later this week.

**Comment by ameyaagashe** [comment]
@mark-amzn Thanks for that. The command work and it produces no output. However, I do not see any task associated with the maintenance window though.

**Comment by mark-amzn** [comment]
@ameyaagashe 

I've verified again that the command format just above with `--task-invocation-parameters` works, running from both my Windows and Linux local machines.

Are you using a third-party tool like GitBash to run commands? I noticed this in your earlier example: `--window-id $grpa_maint_window`. If so, there may be an issue with your setup there that we can't help with.

If you continue to have issues, you may want to contact AWS Support or post your issue in the [Systems Manager Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=185).

-Mark
