### ISSUE TITLE
Access to the path is denied

### ISSUE THREAD

**Issue by BeatKO** [awsdocs/aws-systems-manager-user-guide#138]
Getting error when running the window script

**Get-Content : Access to the path 'C:\ProgramData\Amazon\SSM\InstanceData\registration' is denied.**

But when i run it like this, everything works:
```
Invoke-WebRequest `
    https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgentSetup.exe `
    -OutFile $env:USERPROFILE\Desktop\SSMAgent_latest.exe

Start-Process `
    -FilePath $env:USERPROFILE\Desktop\SSMAgent_latest.exe `
    -ArgumentList "/S"

rm -Force $env:USERPROFILE\Desktop\SSMAgent_latest.exe
Restart-Service AmazonSSMAgent

$code = "code"
$id = "id"
$region = "region"
$dir = $env:TEMP + "\ssm"
New-Item -ItemType directory -Path $dir -Force
cd $dir
(New-Object System.Net.WebClient).DownloadFile("https://amazon-ssm-$region.s3.$region.amazonaws.com/latest/windows_amd64/AmazonSSMAgentSetup.exe", $dir + "\AmazonSSMAgentSetup.exe")
Start-Process .\AmazonSSMAgentSetup.exe -ArgumentList @("/q", "/log", "install.log", "CODE=$code", "ID=$id", "REGION=$region") -Wait
Get-childitem ($env:ProgramData + "\Amazon\SSM\InstanceData\registration")
Get-Service -Name "AmazonSSMAgent"
```

**Comment by tumegan** [comment]
Hello! 

The error you mentioned is due to the user not having access to "C:\ProgramData\Amazon\SSM\InstanceData\registration" so Get-Content command fails. The commands you suggested does not include the Get-Content command, so no error is produced. Perhaps you did not run PowerShell in administrative mode?

If you continue running into this error you might post your issue on the AWS Systems Manager Developer Forums (https://forums.aws.amazon.com/forum.jspa?forumID=185) or consider signing up for AWS technical support: https://aws.amazon.com/premiumsupport/.
