### ISSUE TITLE
ARM links for SLES RPMs not provided

### ISSUE THREAD

**Issue by Phuurl** [awsdocs/aws-systems-manager-user-guide#173]
In the [SSM docs](https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-sles.html), only the addresses for x86_64 packages are provided - arm64 versions are missing.

**Comment by JimbroAmazon** [comment]
Hi Phil, thank you for submitting this issue. Unfortunately, I can't merge the changes because SSM Agent isn't officially supported for ARM64 on SLES: https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html#prereqs-os-linux. But again, thank you for wanting to contribute!
