### ISSUE TITLE
Clarify distinction between filter parameters

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/aws-systems-manager-user-guide#61]
In https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_ListDocuments.html, it lists two different filter parameters with identical descriptions, called `DocumentFilterList` and `Filters`. The two seem to do similar things with subtle differences, and it would be good to explain in the API documentation when a user might want to use one or the other.

**Comment by JimbroAmazon** [comment]
Hi Daniel, 
Thanks for sending along this feedback about the ListDocuments API documentation. I spoke with one of our developers, and he provide me with the following details about the parameters you noted. I've created a task for the Documentation team to update the ListDocuments API description with this information. Thanks!


Document Service ListDocument 
Right now ListDocuments supports two different filters, DocumentFilterList and Filters and they can't be used in one request at the same time, otherwise exception should be thrown.
DocumentFilterList 
DocumentFilterList is deprecated, we are not going to add any new features. 

DocumentFilterList supports filtering document by Name, Owner, PlatformTypes, DocumentType.
Customer can only specify one value for a filter.
e.g. aws ssm list-documents —document-filter-list key=Name,value="test" 
Filters
Filters supports filtering by Name, Owner, PlatformTypes, DocumentType, Tag, TargetType, and we are keeping adding new filter type to it.

Customer can specify multiple values for a filter：

e.g. Given filters f1 = {k1, {v1}}, f2 = {k2,{v2,v3,v4}} , f3 = {k3}
1. ListDocuments( {f1} ): returns resources match k1=v1
2. ListDocuments( {f2} ): returns resources match with k2=v2 OR k2=v3 OR k2=v4. For filter type Owner, only one value is allowed.
3. ListDocuments( {f3} ): the value of f3 is empty, we only allow tag filter value to be null. it returns resources tagged with any tag containing k3 as it's tag key, i.e. the tag k3=*
4. listDocuments( {f1,f2,f3} ): returns resources match with ( k1=v1) AND ( k1=v2 or k1=v3 or k2=v4) AND (k3=*)

e.g. aws ssm list-documents —filters Key=Name,Values=test,doc, this will list all documents which starts with “test” or “doc”

**Comment by copumpkin** [comment]
Ah okay, thank you for the detailed information! The `Filters` option did seem more "standard" (at least based on other AWS APIs I'm familiar with) but I wasn't sure if there was a deeper reason for the other one than just legacy. That makes sense!
